---
# There is a go version of the signal bridge, which is currently in development:
# https://docs.mau.fi/bridges/go/setup.html?bridge=signalgo
# https://docs.mau.fi/bridges/go/signal/index.html

- name: Create system user mautrix-signal
  ansible.builtin.user:
    name: mautrix-signal
    state: present
    system: yes
    home: /opt/mautrix-signal
  become: true

# follow these instructions: https://docs.mau.fi/bridges/python/signal/index.html