---
- name: "mautrix-whatsapp: Create system user"
  ansible.builtin.user:
    name: mautrix-whatsapp
    state: present
    system: yes
    home: /opt/mautrix-whatsapp
  become: true

- name: "mautrix-whatsapp: Download binary"
  ansible.builtin.get_url:
    url: "https://github.com/mautrix/whatsapp/releases/latest/download/mautrix-whatsapp-amd64"
    dest: "/opt/mautrix-whatsapp/mautrix-whatsapp-amd64"
    owner: mautrix-whatsapp
    group: mautrix-whatsapp
    mode: "0755"
  become: true

- name: "mautrix-whatsapp: Check if config.yaml file already exists"
  ansible.builtin.stat:
    path: /opt/mautrix-whatsapp/config.yaml
  register: config_stat

- name: "mautrix-whatsapp: Create config file"
  when:
    - not config_stat.stat.exists
  ansible.builtin.get_url:
    url: https://github.com/mautrix/whatsapp/raw/master/example-config.yaml
    dest: /opt/mautrix-whatsapp/config.yaml
    owner: mautrix-whatsapp
    group: mautrix-whatsapp
    mode: "0600"  # contains passwords
  become: true

- name: "mautrix-whatsapp: Ensure yq is available"
  ansible.builtin.package:
    name: yq
    state: present
  become: true

- name: "mautrix-whatsapp: Set bridge permission dict as fact for next task"
  ansible.builtin.set_fact:
    bridge_permission: "{{ { '*': 'relay', '@' + matrix_user + ':' + matrix_domain: 'admin' } }}"

- name: "mautrix-whatsapp: Adjust config.yaml"
  ansible.builtin.include_tasks: adjust-mautrix-config.yaml
  vars:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    bridge: mautrix-whatsapp
  with_dict:
    - "homeserver.address": "{{ matrix_address }}"
    - "homeserver.domain": "{{ matrix_domain }}"
    - "appservice.database.uri": "postgres://{{ matrix_whatsapp_postgresql_username }}:{{ matrix_whatsapp_postgresql_password }}@{{ matrix_postgresql_hostname }}/{{ matrix_whatsapp_postgresql_database }}?sslmode=disable"
    - "appservice.bot.username": "wabot"
    - "appservice.hostname": "127.0.0.1"
    - "bridge.permissions": "{{ bridge_permission }}"

- name: "mautrix-whatsapp: Create registration.yaml"
  ansible.builtin.include_tasks: create-mautrix-registration.yaml
  vars:
    bridge: "mautrix-whatsapp"
    exec: "/opt/mautrix-whatsapp/mautrix-whatsapp-amd64"

- name: "mautrix-whatsapp: Create service file"
  ansible.builtin.template:
    src: templates/mautrix-go.service.j2
    dest: /etc/systemd/system/{{ bridge }}.service
    owner: root
    group: root
    mode: "0644"
  vars:
    bridge: mautrix-whatsapp
  become: true

- name: "mautrix-whatsapp: Enable and start service"
  ansible.builtin.service:
    name: mautrix-whatsapp
    state: started
    enabled: true
  become: true
